name: Run C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cppcheck:
    name: cppcheck-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
          
      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          
        
      - name: publish report    
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main'

  build:
    runs-on: ubuntu-latest
    steps:
    - name: install build dependencies
      run: |
        sudo apt-get install libcurl4-openssl-dev
        git clone https://github.com/DaveGamble/cJSON.git
        cd cJSON && make && sudo make install
    - name: Check out the repo
      uses: actions/checkout@v4
    - name: Compile the code
      run: make
