name: Run C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cppcheck:
    name: cppcheck-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
          
      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          output_file: ./reports/cppcheck_report.txt

      - name: publish report    
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main'

  flawfinder:
    name: flawfinder-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    
      - name: flawfinder
        uses: david-a-wheeler/flawfinder@2.0.19
        with:
          arguments: '--sarif ./'
          output: './reports/flawfinder_results.sarif'

      - name: publish report    
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main'

  build:
    runs-on: ubuntu-latest
    steps:
      - name: install build dependencies
        run: |
          sudo apt-get install libcurl4-openssl-dev
          git clone https://github.com/DaveGamble/cJSON.git
          cd cJSON && make && sudo make install
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Compile the code
        run: make

  unittest:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: install build dependencies
        run: |
          sudo apt-get install libcurl4-openssl-dev libcunit1 libcunit1-dev
          git clone https://github.com/DaveGamble/cJSON.git
          cd cJSON && make && sudo make install
          sudo ldconfig
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Compile the code
        run: make run_test

      - name: Run Unit tests
        run: ./test/run_test